name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  setup:
    if: "!contains(github.event.head_commit.message, 'ci(skip)')"
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run unit tests
        run: ./gradlew test
